[project]
name = "todo-yorisa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django-environ>=0.12.0",
    "django>=6.0",
]
